export const MAX_PDF_PRESET_INPUT_LENGTH = 8_192;
export const MAX_PDF_PRESET_COMPRESSED_BYTES = 6_144;
export const MAX_PDF_PRESET_JSON_BYTES = 16_384;
export const MAX_PDF_PRESET_NAME_CODE_POINTS = 30;
export const MAX_PDF_PRESET_MEMO_CODE_POINTS = 80;
